// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6LpRPAW9kGUJgy39SDD0ukRDUvGl9uAY',
    appId: '1:211315354078:android:b26e1a8b33917aeca6554f',
    messagingSenderId: '211315354078',
    projectId: 'y-chat-7c175',
    storageBucket: 'y-chat-7c175.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALZhkIz4Y1eiq1vM-EQp1vQwW_Vz0k_WQ',
    appId: '1:211315354078:ios:967ab3849b0e7e95a6554f',
    messagingSenderId: '211315354078',
    projectId: 'y-chat-7c175',
    storageBucket: 'y-chat-7c175.appspot.com',
    androidClientId: '211315354078-93e8bencsops7fgfgmibjj917te9vns0.apps.googleusercontent.com',
    iosClientId: '211315354078-03m4fvt916qkcvagnqgdkll34qfhf7th.apps.googleusercontent.com',
    iosBundleId: 'com.example.ychat',
  );
}
